import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
const [model,destination,theme='editorial']=process.argv.slice(2);
if(!model||!destination||!['default','editorial','blueprint'].includes(theme)) throw new Error('Usage: node generate.mjs model.json output-directory [default|editorial|blueprint]');
const here=path.dirname(fileURLToPath(import.meta.url)),out=path.resolve(destination),input=path.resolve(model);
const run=(name,...args)=>execFileSync(process.execPath,[path.join(here,name),...args],{stdio:'inherit'});
run('render.mjs',input,out);
run('check.mjs',input,out);
run('export-static.mjs',input,out);
if(theme!=='default')run('theme.mjs',out,out,theme);
console.log(`Open ${path.join(out,'share.html')}`);
